chore(deps): add @commitlint/config-conventional & switch yarn with bun

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,4 +2,15 @@
 
 . "$(dirname "$0")/_/husky.sh"
 
+
+# Exit if any command fails
+set -e
+
+# Run ESLint
+echo "Running ESLint..."
 bunx lint-staged
+
+
+# Run Commitlint
+echo "Running Commitlint..."
+bunx commitlint --edit "$1"undefined
